<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\MediaGallery\Commands\**" />
    <EmbeddedResource Remove="Features\MediaGallery\Commands\**" />
    <None Remove="Features\MediaGallery\Commands\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Features\MediaGallery\Commands\DeleteMedia\DeleteMediaCommand.cs" />
    <Compile Include="Features\MediaGallery\Commands\DeleteMedia\DeleteMediaCommandHandler.cs" />
    <Compile Include="Features\MediaGallery\Commands\DeleteMedia\DeleteMediaCommandValidator.cs" />
    <Compile Include="Features\MediaGallery\Commands\UploadMedia\UploadMediaCommand.cs" />
    <Compile Include="Features\MediaGallery\Commands\UploadMedia\UploadMediaCommandHandler.cs" />
    <Compile Include="Features\MediaGallery\Commands\UploadMedia\UploadMediaCommandValidator.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.3" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="10.0.0" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CEIS.Domain\CEIS.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Service\" />
  </ItemGroup>

</Project>
